### ISSUE TITLE
PSCouchDBDocument class bug - New-CouchDBAttachment not found

### ISSUE THREAD

**Issue by jchase-monad** [MatteoGuadrini/PSCouchDB#11]
## Description

Following the example from the Readme.md page, when trying to execute "New-CouchDBAttachment" is recognized as a Cmdlet, script, etc. 

## Steps to Reproduce
From the Readme.md file:

New-CouchDBAttachment -Database test -Document "Hitchhikers" -revision $rev -Attachment C:\file.txt -Authorization "admin:password"

### Powershell Exception

This is traceback exception:
New-CouchDBAttachment: The term 'New-CouchDBAttachment' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### Method used

Execution of the Cmdlet

## Expected Behaviour

Cmdlet to be available.

## Your Environment

* PSCouchDB version used: 3.3.3
* Operating System and version: Ubuntu 24.04 LTS (CouchDB server), Windows 10.0.19044 w/ Powershell 7.4.5

Additional context

**Comment by MatteoGuadrini** [comment]
Hi @jchase-monad,
the cmdlet exists only in the version 1.X of _PSCouchDB_.
In the latest stable version, than is **2.6.0**, the cmdlet is `Add-CouchDBAttachment`.

For instance, to reply your example, the command is:
```powershell
Add-CouchDBAttachment -Database test -Document "Hitchhikers" -revision $rev -Attachment C:\file.txt -Authorization "admin:password"
```

Anyway, you refer the latest stable documentation: [https://pscouchdb.readthedocs.io/en/latest/documents.html#create-an-attachment](https://pscouchdb.readthedocs.io/en/latest/documents.html#create-an-attachment)

```powershell
root@c1b8df945aa9:/# pwsh
PowerShell 7.4.5
PS /> Install-Module -Name PSCouchDB

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change
 its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to
install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
PS /> Enable-CouchDBCluster -SingleNode -Authorization "admin:password"
Enabling single cluster

  ok
  --
True

PS /> New-CouchDBDatabase -Database test -Authorization "admin:password"

  ok
  --
True

PS /> $Data = '{"name": "Arthur Dent","planet": "Heart"}'

PS /> New-CouchDBDocument -Database test -Document "Hitchhikers" -Data $Data -Authorization "admin:password"

  ok id          rev
  -- --          ---
True Hitchhikers 1-0d8fdd0245da9b23da76180a1a2d3909

PS /> $rev = (Get-CouchDBDocument -Database test -Document "Hitchhikers")._rev
PS /> "Ultimate Question of Life, the Universe and Everything" | Out-File file.txt
PS /> Add-CouchDBAttachment -Database test -Document "Hitchhikers" -revision $rev -Attachment file.txt -Authorization "admin:password"

  ok id          rev
  -- --          ---
True Hitchhikers 2-dd50f64d354ec3a52e1ae560cbc056a3
```

I'll fix README asap!
Thanks so mush!
