### ISSUE TITLE
Lack of HTTPS

### ISSUE THREAD

**Issue by thefunc5** [MatteoGuadrini/PSCouchDB#2]
No clear way to enable HTTPS communication. It appears HTTP is set via $url in Send-CouchDBRequest and New-CouchDBReplication. Can we add a parameter to use HTTPS?

**Comment by MatteoGuadrini** [comment]
Hi thefunc5, 
yes, in the coming days I will provide the fix.
Regards

**Comment by MatteoGuadrini** [comment]
Hi thefunc5,
today add SSL capability in all cmdlet. Download the version 1.5.1.
I have decided not to release a tag version. For upgrade, download a zip and copy/replace the file or see the instructions of this [link](https://www.powershellgallery.com/packages/PSCouchDB).
Regards
