### ISSUE TITLE
Export function | Send-CouchDBRequest

### ISSUE THREAD

**Issue by thefunc5** [MatteoGuadrini/PSCouchDB#4]
Please include Send-CouchDBRequest in module exports.

**Comment by MatteoGuadrini** [comment]
Hi theFunc5,
the main reason why I did not export the cmdlet is, _"Simple is better than complex"_ and this cmdlet is complex for those who do not develop or have no general development skills. Furthermore, we need to have some sort of expertise also in json, which not all users have. I prefer to improve and develop other simpler cmdlets. I'm developing ad-hoc powershell objects for the problems you've had. I am also rewriting the **Find** with these objects.
