### ISSUE TITLE
Add support for Views

### ISSUE THREAD

**Issue by thefunc5** [MatteoGuadrini/PSCouchDB#5]
It would be spectacular if we could add support for views!

**Comment by MatteoGuadrini** [comment]
Hi, release [1.7.0](https://github.com/MatteoGuadrini/PSCouchDB/releases/tag/1.7.0) with support a design document. Support also views.
Read a wiki (https://github.com/MatteoGuadrini/PSCouchDB/wiki/pscouchdbdesigndoc#work-with-views) for this!
Thank you very much for your suggestion!
Good work
