### ISSUE TITLE
New-CouchDBDocument "Document must be a JSON object"

### ISSUE THREAD

**Issue by ymmit85** [MatteoGuadrini/PSCouchDB#6]
When adding a new Document and the -data param is provided actual JSON data "Document must be a JSON object" is thrown.

eg: 
$data = Get-Service | select name; $data = $data | convertto-json -compress
New-CouchDBDocument -Server server -Database test -Document "test" -Data $data

Invoke-RestMethod : {"error":"bad_request","reason":"Document must be a JSON object"}
At C:\Program Files\WindowsPowerShell\Modules\PSCouchDB\1.6.0\PSCouchDB.psm1:444 char:16
+     $results = Invoke-RestMethod @options
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by MatteoGuadrini** [comment]
Hi ymmit85,
your is a semantic problem. The conversion in json object is right.
The *real* problem is a type of object that you are converting.
```powershell
$data = Get-Service | select name
$data.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array
```
*$data* is an array json object, but a true json object that's it (see [docs](https://www.json.org/)):
```json
{
    "array": [
        "elem1",
        "elem2"
    ]
}
```
A json object begins with `{` (left brace) and ends with `}` (right brace).
Your converted object start and ends with `[]` brackets (an array json object).
This, is solution for your problem (version 1.6.0):
```powershell
$data = @{Name = @()}
Get-Service | foreach {$data.Name += $_.Name}
$data = $data | ConvertTo-Json -Compress
New-CouchDBDocument -Server server -Database test -Document test -Data $data
```
and here the new version (version 1.7.0):
```powershell
$data = @{Name = @()}
Get-Service | foreach {$data.Name += $_.Name}
New-CouchDBDocument -Server server -Database test -Document test -Data $data
```
I hope I explained better.
Best regards and thanks
