### ISSUE TITLE
Cmdlet fails for CouchDB host with sub dir

### ISSUE THREAD

**Issue by OCram85** [MatteoGuadrini/PSCouchDB#7]
## Description

Cmdlets like `Export-CouchDBDatabase` seems to parse the uri wrong for cases where the CouchDB host is published by a reverse proxy like `https://generic.host.io:443/couch/<db>/<doc>`

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/13993700/122515897-5fc81600-d00e-11eb-9744-2068fe6be30b.png)

### Powershell Exception

This is traceback exception:

## Expected Behaviour

The port itself should be added in the URIs host field an not appended after the path.

## Your Environment

* PSCouchDB version used: 2.3.0
* Operating System and version: Win 10 1909

Additional context

**Comment by MatteoGuadrini** [comment]
Hi @OCram85,
first all, thanks to report this issue, so, I correct this "two minutes ago", ad now available new minor version: [https://www.powershellgallery.com/packages/PSCouchDB/2.3.1](https://www.powershellgallery.com/packages/PSCouchDB/2.3.1)

Now the *-Server* parameter accept subdir and http form "http://mycouchserver.com/test".

Thanks and long live rock'n'roll!

**Comment by OCram85** [comment]
Hi @MatteoGuadrini,

thanks for the quick response. Unfortunately this fix added another issue. Now the auth works, but the request uri seems to be wrong. The database is added twice in the uri :(

![image](https://user-images.githubusercontent.com/13993700/122723436-42e04c80-d273-11eb-8ebe-679ae167246a.png)

**Comment by MatteoGuadrini** [comment]
OMG! An unforgivable oversight! Unfortunately, I never had time to write meaningful unit tests for this module.
I've done some tests on databases, documents and attachments, and it should be fine.
Im very sorry...
New stable release: https://www.powershellgallery.com/packages/PSCouchDB/2.3.2

**Comment by OCram85** [comment]
Awesome work, thanks! This really helps me migrate dbs onto  another host!

![](https://media.giphy.com/media/3oz8xIsloV7zOmt81G/source.gif)
