### ISSUE TITLE
Authorization fails with passwords containing special chars

### ISSUE THREAD

**Issue by OCram85** [MatteoGuadrini/PSCouchDB#8]
## Description

Cmdlets raise an Error whenever the authorization param contains chars like `-`, `!`  in password

## Steps to Reproduce

```powershell
Get-CouchDBDatabase -Database 'foobar' -Sever 'couch.any.io' -Port 5984 -Authorization 'user:foo-bar!'
```
### Powershell Exception

```powershell
Authorization string must be this format: "user:password"
In C:\Program Files\WindowsPowerShell\Modules\pscouchdb\2.3.0\PSCouchDB.psm1:1466 Zeichen:13
+             throw [System.Text.RegularExpressions.RegexMatchTimeoutEx ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RegexMatchTimeoutException
    + FullyQualifiedErrorId : Authorization string must be this format: "user:password"
```

This is traceback exception:

## Expected Behaviour

Description of what is expected

## Your Environment

* PSCouchDB version used: 2.3.0
* Operating System and version: win 10 1909

Additional context

**Comment by MatteoGuadrini** [comment]
Hi @OCram85,
first all, thanks to report this issue, so, I correct this "ten minutes ago", ad now available new minor version: [https://www.powershellgallery.com/packages/PSCouchDB/2.3.1](https://www.powershellgallery.com/packages/PSCouchDB/2.3.1)

Thanks and long live rock'n'roll!
