### ISSUE TITLE
Export & Import cmdlet error due to file format issue

### ISSUE THREAD

**Issue by OCram85** [MatteoGuadrini/PSCouchDB#9]
## 📓 Description

Using `Import-CouchDBDatabase` fails due to json format error generated by `ExportDBDatabase`.

## 🛠️ Steps to Reproduce

```powershell
Export-CouchDBDatabase -Server 'old.couch.io' -Database 'stats' -Verbose -Port 5984 -Authorization (Get-Credential) -Path '.\stats.json'
Import-CouchDBDatabase -Server 'new.couch.io' -Port 443 -Ssl -Database 'stats' -Path .\stats.json -Authorization (Get-Credential) -Verbose -RemoveRevision
```

### 🐛  PowerShell Exception

This is traceback exception:

```
[400] Bad Request: Bad request structure. The error can indicate an error with the request URL, path or headers.
CouchDB Response -> Bad Request
In C:\Program Files\WindowsPowerShell\Modules\pscouchdb\2.3.2\PSCouchDB.psm1:1334 Zeichen:13
+             throw ([PSCouchDBRequestException]::New($errcode.StatusCo ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ([400] Bad Reque... -> Bad Request:String) [], RuntimeException
    + FullyQualifiedErrorId : [400] Bad Request: Bad request structure. The error can indicate an error with the reque
   st URL, path or headers.
CouchDB Response -> Bad Request
```

## ✨  Expected Behaviour

Description of what is expected

## 💻  Your Environment

> 💡 Powershell 5.1 on any Windows system 

* PSCouchDB version used: 2.3.2
* Operating System and version: Any Windows based

##  🧙 PowerShell / Filehandler writes the json ouput file in `UTF8 BOM`, If you manually change the encoding to utf8 *without* BOM the import works!

**Comment by MatteoGuadrini** [comment]
Hi @OCram85,
this issue will be solved if you use powershell core 6.X or 7.X.

As you said Windows Powershell, and for its nature .NET _FileHandler_ object, open json data stream with `UTF8-BOM`. 
This issue could be solved rewriting **PSCouchDBRequest** class, adding the code mentioned in this article: https://debay.blog/2019/10/03/powershell-utf8-and-bom/
but this mean slow down every request to CouchDB server.

I prefer to keep the code clean and I recommend you to use my module with powershell core if you have problems with UTF8 encoding.
Soon and regards
